# Generated by Django 5.2.5 on 2025-09-07 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data de competência da transação'),
        ),
    ]
