# Generated by Django 5.0.7 on 2025-09-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='profissional',
        ),
    ]
