# Generated by Django 5.2.5 on 2025-09-07 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_transacao_data_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Data de competência da transação'),
        ),
    ]
