# Generated by Django 5.2.6 on 2025-09-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_alter_transacao_data_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='lembrete_pagamento_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
