# Generated by Django 5.0.7 on 2025-09-15 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('financas', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='financas.servico'),
        ),
        migrations.AddField(
            model_name='excecaohorario',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excecoes_horario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horariotrabalho',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logmensagemia',
            name='assinatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_mensagens', to='users.assinatura'),
        ),
        migrations.AlterUniqueTogether(
            name='horariotrabalho',
            unique_together={('profissional', 'dia_da_semana')},
        ),
    ]
