# Generated by Django 5.2.6 on 2025-09-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='lembrete_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='token_confirmacao',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
