# Generated by Django 5.0.7 on 2025-09-08 22:00

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Agendamento = apps.get_model('agenda', 'Agendamento')
    for row in Agendamento.objects.all():
        row.token_confirmacao = uuid.uuid4()
        row.save(update_fields=['token_confirmacao'])

class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agendamento_lembrete_enviado_and_more'),
    ]

    operations = [
        # Executa a função para preencher os tokens nos registos existentes
        migrations.RunPython(gen_uuid),
    ]
