# Generated by Django 5.2.6 on 2025-09-09 00:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_populate_uuid_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='token_confirmacao',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
