# Generated by Django 5.2.6 on 2025-09-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='follow_up_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
