# Generated by Django 5.0.7 on 2025-09-15 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_excecaohorario_horariotrabalho'),
        ('users', '0005_plano_assinatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMensagemIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('sid_twilio', models.CharField(max_length=255, unique=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_mensagens', to='users.assinatura')),
            ],
        ),
    ]
