# Generated by Django 5.0.7 on 2025-09-15 23:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIARIO', 'Intermediário'), ('PREMIUM', 'Premium')], max_length=50, unique=True)),
                ('limite_usuarios', models.PositiveIntegerField(default=1)),
                ('limite_mensagens_ia', models.PositiveIntegerField(default=0)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de email')),
                ('nome_completo', models.CharField(max_length=255)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_profissional', models.CharField(blank=True, max_length=50, null=True, verbose_name='registro profissional (CRP, CREFITO, etc.)')),
                ('contato_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='profissional_set', related_query_name='profissional', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='profissional_set', related_query_name='profissional', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conta', models.CharField(help_text='Nome da clínica ou do profissional', max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('proprietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_proprietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profissional',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='users.conta'),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('contato_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('endereco', models.TextField(blank=True, null=True)),
                ('dia_cobranca', models.IntegerField(blank=True, help_text='Dia do mês para geração da fatura agrupada (de 1 a 31). Deixe em branco para cobrança imediata.', null=True, verbose_name='Dia de Cobrança Mensal')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('conversation_state', models.CharField(blank=True, help_text='Controla o estado da conversa com a IA', max_length=50, null=True)),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='users.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('conta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='users.conta')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.plano')),
            ],
        ),
    ]
