# Generated by Django 5.0.7 on 2025-09-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='funcao',
            field=models.CharField(choices=[('proprietario', 'Proprietário'), ('profissional', 'Profissional')], default='profissional', help_text='Define o nível de permissão do usuário na conta.', max_length=20),
        ),
    ]
