# Generated by Django 5.0.7 on 2025-09-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profissional_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número de WhatsApp da clínica (formato: 55119...)', max_length=20, null=True, unique=True),
        ),
    ]
