# Generated by Django 5.2.5 on 2025-09-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profissional_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dia_cobranca',
            field=models.IntegerField(blank=True, help_text='Dia do mês para geração da fatura agrupada (de 1 a 31). Deixe em branco para cobrança imediata.', null=True, verbose_name='Dia de Cobrança Mensal'),
        ),
    ]
