# Generated by Django 5.0.7 on 2025-09-20 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_conta_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_faq', to='users.conta')),
            ],
            options={
                'verbose_name': 'Categoria do FAQ',
                'verbose_name_plural': 'Categorias do FAQ',
            },
        ),
        migrations.CreateModel(
            name='ItemFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intencao_chave', models.CharField(help_text="Uma palavra-chave única para a IA identificar a intenção. Ex: 'verificar_convenios' (use apenas letras minúsculas e underscore)", max_length=100)),
                ('perguntas_exemplo', models.TextField(help_text='Exemplos de perguntas que os pacientes fazem, separadas por ponto e vírgula (;).')),
                ('resposta', models.TextField(help_text='A resposta exata que a secretária IA deve dar.')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='users.categoriafaq')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_faq', to='users.conta')),
            ],
            options={
                'verbose_name': 'Item do FAQ',
                'verbose_name_plural': 'Itens do FAQ',
                'unique_together': {('conta', 'intencao_chave')},
            },
        ),
    ]
