# Generated by Django 5.0.7 on 2025-09-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paciente_dia_cobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='conversation_state',
            field=models.CharField(blank=True, help_text='Controla o estado da conversa com a IA', max_length=50, null=True),
        ),
    ]
