# Generated by Django 5.0.7 on 2025-09-21 22:46

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_categoriafaq_itemfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Uma breve descrição sobre a clínica ou profissional.', null=True)),
                ('endereco_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('instagram_handle', models.CharField(blank=True, help_text="Apenas o nome de usuário, sem o '@'.", max_length=100, null=True)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to=apps.users.models.logo_directory_path)),
                ('conta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='users.conta')),
            ],
        ),
    ]
