# Generated by Django 5.0.7 on 2025-09-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_perfilclinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='onboarding_step',
            field=models.CharField(blank=True, help_text='Controla a etapa do onboarding do paciente via IA', max_length=50, null=True),
        ),
    ]
