# Generated by Django 5.0.7 on 2025-09-22 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_perfilclinica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitacao', models.CharField(choices=[('RECEITA', 'Receita'), ('ATESTADO', 'Atestado/Declaração'), ('RECIBO', 'Recibo para Reembolso'), ('OUTRO', 'Outro')], max_length=50)),
                ('detalhes', models.TextField(blank=True, help_text='Detalhes adicionais fornecidos pelo paciente ou IA.', null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='users.conta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='users.paciente')),
                ('profissional_atribuido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Paciente',
                'verbose_name_plural': 'Solicitações de Pacientes',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
